services:
  php-fpm:
    container_name: php-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code

  nginx:
    container_name: nginx-container
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    container_name: mysql-container
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=encore
